In [0]:
import torch
import numpy as np
import itertools as it
import unittest

In [0]:
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'C', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])

In [3]:
N = 6
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'C', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
#dna1 = ["ATGCGA","CAGTGC","TTATGT","AGAAGG","CCCCTA","TCACTG"]
unique, indices, counts = np.unique(mutante1, return_inverse=True, return_counts=True, axis=None)
print(f"With numpy.unique\n{mutante1}\n{unique}{unique.shape}\n{indices}{indices.shape}\n{counts}{counts.shape}")

# mutante1 = torch.from_numpy(unique)
# unique, indices, counts = torch.unique(mutante1, return_inverse=True, return_counts=True)
# print(f"With torch.unique:\n{mutante1}\n{unique}{unique.shape}\n{indices}{indices.shape}\n{counts}{counts.shape}")


With numpy.unique
[['A' 'T' 'G' 'C' 'G' 'A']
 ['C' 'A' 'G' 'T' 'G' 'C']
 ['T' 'T' 'A' 'T' 'G' 'T']
 ['A' 'G' 'A' 'A' 'C' 'C']
 ['C' 'C' 'C' 'C' 'T' 'A']
 ['T' 'C' 'A' 'C' 'T' 'G']]
['A' 'C' 'G' 'T'](4,)
[0 3 2 1 2 0 1 0 2 3 2 1 3 3 0 3 2 3 0 2 0 0 1 1 1 1 1 1 3 0 3 1 0 1 3 2](36,)
[ 9 11  7  9](4,)


In [4]:
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'C', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
unique = np.unique(mutante1)
print(f"{unique}")
np.isin(unique, ['A','C','G','T']).all()

['A' 'C' 'G' 'T']


True

In [5]:
dna2 = ["ATGCGA","CAGTGC","TTATGT","AGAACC","CCCCTA","TCACTG"]
mutante1_CC = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'C', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
unique, indices, counts = np.unique(mutante1_CC, return_inverse=True, return_counts=True)
mutante1_CC = indices.reshape(N,N)
mutante1_CC = torch.as_tensor(mutante1_CC, device=torch.device('cpu'))
print(mutante1_CC)

tensor([[0, 3, 2, 1, 2, 0],
        [1, 0, 2, 3, 2, 1],
        [3, 3, 0, 3, 2, 3],
        [0, 2, 0, 0, 1, 1],
        [1, 1, 1, 1, 3, 0],
        [3, 1, 0, 1, 3, 2]])


**Below cell returns whether a row has a group of elements. We should filter if a group size is > 4**

In [6]:
unique_consecutive, counts = torch.unique_consecutive(mutante1_CC, return_counts=True)
print(f"{mutante1_CC}\n{unique_consecutive}{unique_consecutive.shape}\n{counts}{counts.shape}")
#the previous line return 6 for CC in row3 + CCCCC in row 4 which is not OK. It don't consider initial tensor shape which is wrong.
# and the dim parameter doesn't serve for that purpouse.


tensor([[0, 3, 2, 1, 2, 0],
        [1, 0, 2, 3, 2, 1],
        [3, 3, 0, 3, 2, 3],
        [0, 2, 0, 0, 1, 1],
        [1, 1, 1, 1, 3, 0],
        [3, 1, 0, 1, 3, 2]])
tensor([0, 3, 2, 1, 2, 0, 1, 0, 2, 3, 2, 1, 3, 0, 3, 2, 3, 0, 2, 0, 1, 3, 0, 3,
        1, 0, 1, 3, 2])torch.Size([29])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 6, 1, 1, 1,
        1, 1, 1, 1, 1])torch.Size([29])


In [7]:
##### numpy unique
import numpy as np
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'G'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
u, indices, counts = np.unique(mutante1, return_inverse=True, return_counts=True)
print(f'unique: {u}, type:{type(u[0])}')
print(f'indices: \n{indices.reshape(6,6)}')
print(f'counts: {counts}')
print(f'data: \n{u[indices].reshape(6,6)}')


unique: ['A' 'C' 'G' 'T'], type:<class 'numpy.str_'>
indices: 
[[0 3 2 1 2 0]
 [1 0 2 3 2 1]
 [3 3 0 3 2 3]
 [0 2 0 0 2 2]
 [1 1 1 1 3 0]
 [3 1 0 1 3 2]]
counts: [9 9 9 9]
data: 
[['A' 'T' 'G' 'C' 'G' 'A']
 ['C' 'A' 'G' 'T' 'G' 'C']
 ['T' 'T' 'A' 'T' 'G' 'T']
 ['A' 'G' 'A' 'A' 'G' 'G']
 ['C' 'C' 'C' 'C' 'T' 'A']
 ['T' 'C' 'A' 'C' 'T' 'G']]


In [0]:
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'G'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])

In [0]:
mutante2 = np.array([['T', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'G'],
                 ['C', 'C', 'C', 'C', 'A', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])

In [10]:
alpha_num = list('-')
adn_base_test = ['*']
mutante = np.random.choice(alpha_num, size=[N, N])
np.fill_diagonal(mutante, ['*', '*', '-', '*', '*', '-' ])
np.fill_diagonal(np.fliplr(mutante), ['*', '*', '-', '*', '*', '-' ])
mutante[0] = ['*', '-', '*', '*', '*', '-' ]
mutante[N-1] = ['*', '*', '-', '*', '*', '-' ]
mutante[:, N-1] = ['-', '-', '-', '*', '*', '-' ]
print(mutante, type(mutante))
#patterns: 7 positivios en diagonales, filas: 5, cols: 4. Total 16 de largo 2
# Total 3 de largo 3

[['*' '-' '*' '*' '*' '-']
 ['-' '*' '-' '-' '*' '-']
 ['-' '-' '-' '-' '-' '-']
 ['-' '-' '*' '*' '-' '*']
 ['-' '*' '-' '-' '*' '*']
 ['*' '*' '-' '*' '*' '-']] <class 'numpy.ndarray'>


In [11]:
print(np.shape(mutante1))
print(len(np.diagonal(mutante1))-2)

(6, 6)
4


In [0]:
def mutant_count(adn_matrix, adn_base=['A', 'C', 'G', 'T'], adn_seq_length=4):
    N = len(adn_matrix)
    # ACGT_count = np.count_nonzero(np.logical_or(np_adn == 'A', np_adn == 'T')) +  np.count_nonzero(np.logical_or(np_adn ==  'C', np_adn ==  'G'))

    # if (ACGT_count != N*N):
    #     return None
    unique = np.unique(adn_matrix)
    if not(np.isin(unique, adn_base).all()):
      print(f"notisin:{unique, adn_base}")
      return None

    match_count = 0

    # l: letter, g: group
    # main diagonals
    match_count += np.sum(
        [len(list(g))  >= adn_seq_length 
        for l, g in it.groupby(np.diagonal(adn_matrix,offset=0)) 
        if l in adn_base])

    match_count += np.sum(
        [len(list(g))  >= adn_seq_length 
        for l, g in it.groupby(np.fliplr(adn_matrix).diagonal(offset=0)) 
        if l in adn_base])

    # Diagonals without main diagonals
    max_diag_size = range(1, N-adn_seq_length+1 )
    for i in range(1, N-adn_seq_length+1): 
        # l: letter, g: group
        # left to right upper diagonals
        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(np.diagonal(adn_matrix,offset=i)) 
            if l in adn_base])
        
        # # left to right lower diagonals
        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(np.diagonal(adn_matrix,offset=-i)) 
            if l in adn_base])

        #right to left upper diagonals
        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(np.fliplr(adn_matrix).diagonal(offset=i)) 
            if l in adn_base])

        # #right to left lower diagonals
        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(np.fliplr(adn_matrix).diagonal(offset=-i)) 
            if l in adn_base])
        
    # Remaining rows and columns
    for i in range(1, N+1):
        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(adn_matrix[i-1,:]) 
            if l in adn_base])

        match_count += np.sum(
            [len(list(g))  >= adn_seq_length 
            for l, g in it.groupby(adn_matrix[:,i-1]) 
            if l in adn_base])
        
    return int(match_count)


** #################### START OF UNIT TESTS #################### **


In [13]:
import unittest
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
mutante2 = np.array(
                [['T', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'C'],
                 ['C', 'C', 'C', 'C', 'A', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
N = 6
sequence_length = 2
alpha_num = list('-')
adn_base_test = ['*']

mutante3 = np.random.choice(alpha_num, size=[N, N])
np.fill_diagonal(mutante3, ['*', '*', '-', '*', '*', '-' ])
np.fill_diagonal(np.fliplr(mutante3), ['*', '*', '-', '*', '*', '-' ])
mutante3[0] = ['*', '-', '*', '*', '*', '-' ]
mutante3[N-1] = ['*', '*', '-', '*', '*', '-' ]
mutante3[:, N-1] = ['-', '-', '-', '*', '*', '-' ]
#patterns: 7 positivios en diagonales, filas: 5, cols: 4. Total 16 de largo 2
# Total 3 de largo 3


mutant_function = mutant_count  

class TestMethods(unittest.TestCase):
    
    ##########
    # Unit tests
    ##########
    
    def test_mutant_count_asterisk_36(self):
        self.assertTrue(
            mutant_function(mutante3, adn_base=['*', '-'], adn_seq_length=2) == 36 
        )
    
    def test_mutant_count_asterisk_11(self):
        self.assertTrue(
            mutant_function(mutante3, adn_base=['*', '-'], adn_seq_length=3) == 11 
        )
        
   
suite = unittest.TestLoader().loadTestsFromModule(TestMethods())
unittest.TextTestRunner().run(suite)

..
----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK


<unittest.runner.TextTestResult run=2 errors=0 failures=0>

In [14]:
import unittest
mutante1 = np.array(
                [['A', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'C'],
                 ['C', 'C', 'C', 'C', 'T', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
mutante2 = np.array(
                [['T', 'T', 'G', 'C', 'G', 'A'], 
                 ['C', 'A', 'G', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['A', 'G', 'A', 'A', 'G', 'C'],
                 ['C', 'C', 'C', 'C', 'A', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])
mutante3 = np.array(
                [['T', 'T', 'G', 'T', 'G', 'A'], 
                 ['C', 'A', 'T', 'T', 'G', 'C'],
                 ['T', 'T', 'A', 'T', 'G', 'T'], 
                 ['T', 'G', 'A', 'A', 'G', 'C'],
                 ['C', 'C', 'C', 'C', 'A', 'A'],
                 ['T', 'C', 'A', 'C', 'T', 'G']])

mutante4 = np.random.choice(['A'], size=[6, 6])


mutant_function = mutant_count  

class TestMethods(unittest.TestCase):
    
    ##########
    # Unit tests
    ##########
        
    def test_mutant_count_dna_3(self):
        self.assertTrue(
            mutant_function(mutante1) == 3 
        )
     
    def test_mutant_count_dna_3_bis(self):
        self.assertTrue(
            mutant_function(mutante2) == 3 
        )

    def test_mutant_count_dna_18(self):
        self.assertTrue(
            mutant_function(mutante3, adn_seq_length=2) == 18 
        )

    def test_mutant_count_dna_6(self):
        self.assertTrue(
            mutant_function(mutante3, adn_seq_length=3) == 6 
        )

    def test_mutant_count_dna_4(self):
        self.assertTrue(
            mutant_function(mutante3, adn_seq_length=4) == 4 
        )    

    def test_mutant_count_dna_22(self):
        self.assertTrue(
            mutant_function(mutante4, adn_base=['A']) == 22 
        )
suite = unittest.TestLoader().loadTestsFromModule(TestMethods())
unittest.TextTestRunner().run(suite)

......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK


<unittest.runner.TextTestResult run=6 errors=0 failures=0>